### ISSUE TITLE
Server assumes at least one entry in the whitelist

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#127]
Not sure if this has anything to do with my installation but I recently re-installed the Nintendo server on my RPi and I cloned from my git (the one with the script) and I get this lovely error when I try connecting to it

[2015-04-15 18:43:09 | GamespyDatabase] [HsgKyP1j] STARTING: SELECT \* FROM users WHERE userid = 0788854533918 and gameid = RMCJ and enabled = 0 and gameid not in (select gameid from whitelist where gameid=RMCJ and macadr=0017ab948d4d) limit 1
[2015-04-15 18:43:09 | GameSpyProfileServer] [192.168.101.197:60108] Unknown exception: Traceback (most recent call last):
  File "/home/pi/dwc_network_server_emulator/gamespy_profile_server.py", line 193, in rawDataReceived
    cmds.get(data_parsed['**cmd**'], cmd_err)(data_parsed)
  File "/home/pi/dwc_network_server_emulator/gamespy_profile_server.py", line 223, in perform_login
    userid, profileid, gsbrcd, uniquenick = gs_utils.login_profile_via_parsed_authtoken(authtoken_parsed, self.db)
  File "/home/pi/dwc_network_server_emulator/gamespy/gs_utility.py", line 132, in login_profile_via_parsed_authtoken
    profileid = db.create_user(userid, password, email, uniquenick, gsbrcd, console, csnum, cfc, bssid, devname, birth, gameid, macadr)
  File "/home/pi/dwc_network_server_emulator/gamespy/gs_database.py", line 215, in create_user
    ,(userid, gameid, gameid, macadr))
  File "/home/pi/dwc_network_server_emulator/gamespy/gs_database.py", line 80, in queryone
    self._executeAndMeasure(cursor, statement, parameters)
  File "/home/pi/dwc_network_server_emulator/gamespy/gs_database.py", line 59, in _executeAndMeasure
    cursor.execute(statement, parameters)
OperationalError: no such table: whitelist

[2015-04-15 18:44:21 | GameSpyProfileServer] [192.168.101.197:60108] Client disconnected
[2015-04-15 18:44:21 | GamespyDatabase] [WPl2vloo] STARTING: SELECT \* FROM buddies WHERE userProfileId = 0 AND blocked = 0
[2015-04-15 18:44:21 | GamespyDatabase] [WPl2vloo] DONE: Took 0.00173497200012 real time / 0.0 processor time
[2015-04-15 18:44:21 | GamespyDatabase] [u0dRzfZI] STARTING: DELETE FROM sessions WHERE profileid = 
[2015-04-15 18:44:21 | GamespyDatabase] [u0dRzfZI] DONE: Took 0.00135803222656 real time / 0.0 processor time
[2015-04-15 18:44:21 | GameSpyProfileServer] [192.168.101.197:60108] Deleted session 

Ingame I get error 61070 (in my world it means banned)

**Comment by kyle95wm** [comment]
I've also had instances where I would delete the db file, restart master and not get the error but I'm stuck at the "login" action and eventually get "timed out" perhaps this is because of the many limitations of my Pi's hardware but Im not willing to accept that

**Comment by kyle95wm** [comment]
Okay so I just tried this on an Ubuntu VM (same setup script obviously) and I GOT the error about the white list so here's what I found:

Basically it turns out that you're REQUIRED to at least have ONE entry in the white list otherwise it will all go to hell in the end. On another note Im still confused as to why the server gets "stuck" on the Pi I highly doubt its a hardware problem, but more like the server is expecting the same thing as stated above.

@SMTDDR is a genius when it comes to this white list thing since he was the one who made it

**Comment by PhynixP** [comment]
Hello i have the Same Problem
But it Works , when I type Userid gameid usw. To the Whitelist.

**Comment by SMTDDR** [comment]
@kyle95wm 

What error do you see?

**Comment by SMTDDR** [comment]
@kyle95wm 
Oh... I see.... no table called whitelist.. hmm.

**Comment by SMTDDR** [comment]
@kyle95wm 

This should fix it: https://github.com/polaris-/dwc_network_server_emulator/pull/128

**Comment by kyle95wm** [comment]
Ah gotcha. Just wish I can merge it with my own repo

**Comment by tokunbo** [comment]
@kyle95wm 
You can,  https://help.github.com/articles/syncing-a-fork/

cd into your local copy of dwc. "git fetch upstream" then use git cherry-pick.
The URL for this commit on polaris- master is : https://github.com/polaris-/dwc_network_server_emulator/commit/037a647b74ae62cc38c6d87bc6ef14bb81a39b41

So you'd type <code>git cherry-pick 037a647b74ae62cc38c6d87bc6ef14bb81a39b41</code>

**Comment by SMTDDR** [comment]
@kyle95wm 
You can,  https://help.github.com/articles/syncing-a-fork/

cd into your local copy of dwc. <code>git fetch upstream</code> then use git cherry-pick.
The URL for this commit on polaris- master is : https://github.com/polaris-/dwc_network_server_emulator/commit/037a647b74ae62cc38c6d87bc6ef14bb81a39b41

So you'd type <code>git cherry-pick 037a647b74ae62cc38c6d87bc6ef14bb81a39b41</code>
