### ISSUE TITLE
Find DNS address

### ISSUE THREAD

**Issue by DevEkode** [barronwaffles/dwc_network_server_emulator#135]
A simple question, i'm a newbie and i install my VPS ubuntu and my question is
 Where find you the DNS address?

**Comment by kyle95wm** [comment]
if you're using a VPS it would be your external IP which can be found at http://cmyip.com or maybe your provider has provided you with a static address. I don't really know too much about VPS but @SMTDDR defiantly does.

**Comment by DevEkode** [comment]
that's what I thought but still I get the following message:
 [GameSpyProfileServer] Now listening for connections on 0.0.0.0:29900...

**Comment by kyle95wm** [comment]
That message is normal. Basically all 0's means it's listening for any connections from any address

**Comment by DevEkode** [comment]
ok thanks, I'll try to connect with a DS emulator (Desmume WIFI)

**Comment by DevEkode** [comment]
strange, I get the error code 20998

**Comment by DevEkode** [comment]
ok, new things appeared in the console when i tried to connect to my vps:

[2015-04-21 11:11:17 | NasServer] Request to /ac from ('127.0.0.1', 45559)
[2015-04-21 11:11:17 | NasServer] {'lang': '02', 'gamecd': 'AMCP', 'makercd': '01', 'unitcd': '0', 'bssid': '00f01a2b3c4d', 'passwd': '928', 'devname': 'y\x00o\x00p\x00y\x00o\x00p\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'userid': '3405195916006', 'macadr': '0009bf123456', 'apinfo': '00:0000000-0', 'devtime': '150421111114', 'birth': '070f', 'action': 'acctcreate', 'sdkver': '001000'}
127.0.0.1 - - [21/Apr/2015 11:11:17] "POST /ac HTTP/1.1" 200 -
[2015-04-21 11:11:17 | GamespyDatabase] [7nlj45PY] STARTING: SELECT max(userid) FROM users
[2015-04-21 11:11:17 | GamespyDatabase] [7nlj45PY] DONE: Took 0.000425100326538 real time / 0.0 processor time
[2015-04-21 11:11:17 | NasServer] Unknown exception: Traceback (most recent call last):
  File "/root/dwc_network_server_emulator/nas_server.py", line 105, in do_POST
    ret['userid'] = self.server.db.get_next_available_userid()
  File "/root/dwc_network_server_emulator/gamespy/gs_database.py", line 417, in get_next_available_userid
    userid = str(int(json.loads(r['max(userid)'])) + 1)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

**Comment by SMTDDR** [comment]
@codevirtuel Does it still give you that error?

**Comment by DevEkode** [comment]
look my new issue
