### ISSUE TITLE
Error when running on windows 10 - need help

### ISSUE THREAD

**Issue by buhiroshi0205** [barronwaffles/dwc_network_server_emulator#275]
I installed twisted, zope interface, pypiwin32 with python2.7 amd64. However when I run master_server.py, this error comes out with error code 10038.

[2016-03-20 17:00:38 | GameSpyQRServer] Unknown exception: Traceback (most recent call last):
  File "C:\Users\buhiroshi0205\Desktop\nintendo_server\server\gamespy_qr_server.py", line 103, in start
    self.server_manager.connect()
  File "C:\Python27\lib\multiprocessing\managers.py", line 500, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "C:\Python27\lib\multiprocessing\connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "C:\Python27\lib\multiprocessing\connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 10038]

Traceback (most recent call last):
  File "C:\Users\buhiroshi0205\Desktop\nintendo_server\server\master_server.py", line 69, in <module>
    threading.Thread(target=server().start).start()
  File "C:\Users\buhiroshi0205\Desktop\nintendo_server\server\gamespy_natneg_server.py", line 65, in **init**
    self.server_manager.connect()
  File "C:\Python27\lib\multiprocessing\managers.py", line 500, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "C:\Python27\lib\multiprocessing\connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "C:\Python27\lib\multiprocessing\connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 10038]

I did not install apache or dnsmasq (what is that) or make any other dns settings.
Any help would be appreciated. Thank you!

**Comment by BadBreath69** [comment]
you need apache to fix the error and dnsmasq is required for connecting with your server.

**Comment by buhiroshi0205** [comment]
OK I'll try that! Thank you!

**Comment by kyle95wm** [comment]
I'm not entirely sure there is such a program like DNSMASQ for Windows. This is why Linux is always better server-wise.

**Comment by BadBreath69** [comment]
Wfcpatcher could work

**Comment by buhiroshi0205** [comment]
idk why I left this open for more than a year. Closing.

I was busy so I didn't get the time to investigate this issue further yet. But I'll probably just switch to linux. If I obtain any new useful information I'll update it here.
