### ISSUE TITLE
[Error Code: 85010] Boom Street Matchmaking

### ISSUE THREAD

**Issue by sepalani** [barronwaffles/dwc_network_server_emulator#277]
I tried Boom Street matchmaking and discovered there are errors in the GameSpyServerBrowserServer.

```
[2016-03-22 12:38:36 | GameSpyServerBrowserServer] [127.0.0.1:4389] Unknown exception:
Traceback (most recent call last):
  File "S:\Projects\dwc_network_server_emulator\gamespy_server_browser_server.py
", line 256, in rawDataReceived
    max_servers, game_name, challenge)
  File "S:\Projects\dwc_network_server_emulator\gamespy_server_browser_server.py
", line 424, in find_server
    query_game, filter, fields, max_servers
  File "C:\Python27\lib\multiprocessing\managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "C:\Python27\lib\multiprocessing\managers.py", line 567, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "C:\Python27\lib\multiprocessing\managers.py", line 105, in dispatch
    raise convert_to_error(kind, result)
RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\managers.py", line 207, in handle_reques
t
    result = func(c, *args, **kwds)
  File "C:\Python27\lib\multiprocessing\managers.py", line 386, in create
    obj = callable(*args, **kwds)
  File "S:\Projects\dwc_network_server_emulator\gamespy_backend_server.py", line
 390, in find_servers
    m = ast.parse(q, "<string>", "exec")
  File "C:\Python27\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<string>", line 1
    90 == 90 and 16 != 16 and 3 == 3 and 0 < 3 and 0 == 0 and 0 == 0 and 0 == 2
and ( ( '102' LIKE '102' ) and ( "AL" LIKE 'AL' ) and ( '1' LIKE '1' ) and ( '2'
 LIKE '2' ) and ( '0' LIKE '0' ) and '1' == '1' )

                 ^
SyntaxError: invalid syntax
---------------------------------------------------------------------------
```

**EDIT:** I found the issue. The backend server doesn't handle "LIKE".

**Comment by polaris-** [comment]
This is the first time I've ever seen the LIKE command. I sanitize and turn the search string into Python for execution so the LIKE command would need to be replaced with an equivalent Python code.  I'm not really sure what the LIKE command is really doing here, though. Unless it's the same as an equality check?

**Comment by mm201** [comment]
http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html

It's basically a string matching function with special syntax. You should be able to parse it into a regex.
