### ISSUE TITLE
Error when running master_server.py

### ISSUE THREAD

**Issue by TheShah18** [barronwaffles/dwc_network_server_emulator#554]
I have consistently gotten this error whenever I try to launch the master_server.py file even if Python2.7 is run as administrator

Here's a sample of the code:
[2021-10-06 10:58:40 | AdminPage] adminpageconf.json not found. Admin page will not be available.
[2021-10-06 10:58:40 | GamespyDatabase] [Sfzjmc9u] STARTING: CREATE TABLE IF NOT EXISTS users (profileid INT, userid TEXT, password TEXT, gsbrcd TEXT, email TEXT, uniquenick TEXT, pid TEXT, lon TEXT, lat TEXT, loc TEXT, firstname TEXT, lastname TEXT, stat TEXT, partnerid TEXT, console INT, csnum TEXT, cfc TEXT, bssid TEXT, devname BLOB, birth TEXT, gameid TEXT, enabled INT, zipcode TEXT, aim TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [Sfzjmc9u] DONE: Took 0.0 real time / 0.0011414 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [m5a8onDJ] STARTING: CREATE TABLE IF NOT EXISTS sessions (session TEXT, profileid INT, loginticket TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [m5a8onDJ] DONE: Took 0.0 real time / 0.0004418 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [OQcr3v6x] STARTING: CREATE TABLE IF NOT EXISTS buddies (userProfileId INT, buddyProfileId INT, time INT, status INT, notified INT, gameid TEXT, blocked INT)
[2021-10-06 10:58:40 | GamespyDatabase] [OQcr3v6x] DONE: Took 0.0 real time / 0.0004529 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [RQQIwzMw] STARTING: CREATE TABLE IF NOT EXISTS pending_messages (sourceid INT, targetid INT, msg TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [RQQIwzMw] DONE: Took 0.0 real time / 0.0004967 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [mxdcR8uZ] STARTING: CREATE TABLE IF NOT EXISTS gamestat_profile (profileid INT, dindex TEXT, ptype TEXT, data TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [mxdcR8uZ] DONE: Took 0.0 real time / 0.0004297 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [VKQHpdah] STARTING: CREATE TABLE IF NOT EXISTS gameinfo (profileid INT, dindex TEXT, ptype TEXT, data TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [VKQHpdah] DONE: Took 0.0 real time / 0.0004309 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [pXjciydI] STARTING: CREATE TABLE IF NOT EXISTS nas_logins (userid TEXT, authtoken TEXT, data TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [pXjciydI] DONE: Took 0.0 real time / 0.0004274 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [NoktMZfI] STARTING: CREATE TABLE IF NOT EXISTS banned (gameid TEXT, ipaddr TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [NoktMZfI] DONE: Took 0.0 real time / 0.0004386 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [8neXeuaR] STARTING: CREATE TABLE IF NOT EXISTS pending (macadr TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [8neXeuaR] DONE: Took 0.0 real time / 0.0004249 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [S0U1u0nw] STARTING: CREATE TABLE IF NOT EXISTS registered (macadr TEXT)
[2021-10-06 10:58:40 | GamespyDatabase] [S0U1u0nw] DONE: Took 0.0 real time / 0.0004761 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [6QnTYUcC] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS gamestatprofile_triple ON gamestat_profile(profileid,dindex,ptype)
[2021-10-06 10:58:40 | GamespyDatabase] [6QnTYUcC] DONE: Took 0.0 real time / 0.0004636 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [5cMdIAbu] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS users_profileid_idx ON users (profileid)
[2021-10-06 10:58:40 | GamespyDatabase] [5cMdIAbu] DONE: Took 0.0 real time / 0.0004576 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [G7NxXlqU] STARTING: CREATE INDEX IF NOT EXISTS users_userid_idx ON users (userid)
[2021-10-06 10:58:40 | GamespyDatabase] [G7NxXlqU] DONE: Took 0.0 real time / 0.0005464 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [bnyz0MtI] STARTING: CREATE INDEX IF NOT EXISTS pending_messages_targetid_idx ON pending_messages (targetid)
[2021-10-06 10:58:40 | GamespyDatabase] [bnyz0MtI] DONE: Took 0.0 real time / 0.0005822 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [X88F3DlT] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS sessions_session_idx ON sessions (session)
[2021-10-06 10:58:40 | GamespyDatabase] [X88F3DlT] DONE: Took 0.0 real time / 0.0004814 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [fZq04oDS] STARTING: CREATE INDEX IF NOT EXISTS sessions_loginticket_idx ON sessions (loginticket)
[2021-10-06 10:58:40 | GamespyDatabase] [fZq04oDS] DONE: Took 0.0 real time / 0.0004521 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [C8D3txSi] STARTING: CREATE INDEX IF NOT EXISTS sessions_profileid_idx ON sessions (profileid)
[2021-10-06 10:58:40 | GamespyDatabase] [C8D3txSi] DONE: Took 0.0 real time / 0.0004366 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [lQM0Uw9h] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS nas_logins_authtoken_idx ON nas_logins (authtoken)
[2021-10-06 10:58:40 | GamespyDatabase] [lQM0Uw9h] DONE: Took 0.0 real time / 0.0004338 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [3CvSXhSR] STARTING: CREATE INDEX IF NOT EXISTS nas_logins_userid_idx ON nas_logins (userid)
[2021-10-06 10:58:40 | GamespyDatabase] [3CvSXhSR] DONE: Took 0.0 real time / 0.0004697 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [2SuESlz1] STARTING: CREATE INDEX IF NOT EXISTS buddies_userProfileId_idx ON buddies (userProfileId)
[2021-10-06 10:58:40 | GamespyDatabase] [2SuESlz1] DONE: Took 0.0 real time / 0.0006011 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [TMjeQVGC] STARTING: CREATE INDEX IF NOT EXISTS buddies_buddyProfileId_idx ON buddies (buddyProfileId)
[2021-10-06 10:58:40 | GamespyDatabase] [TMjeQVGC] DONE: Took 0.0 real time / 0.000481 processor time
[2021-10-06 10:58:40 | GamespyDatabase] [vMFe92y7] STARTING: CREATE INDEX IF NOT EXISTS gamestat_profile_profileid_idx ON gamestat_profile (profileid)
[2021-10-06 10:58:40 | GamespyDatabase] [vMFe92y7] DONE: Took 0.0 real time / 0.0004539 processor time
[2021-10-06 10:58:40 | GamespyBackendServer] Started server on 127.0.0.1:27500...
[2021-10-06 10:58:40 | GameSpyProfileServer] Now listening for connections on 0.0.0.0:29900...
[2021-10-06 10:58:40 | GameSpyPlayerSearchServer] Now listening for player search connections on 0.0.0.0:29901...
[2021-10-06 10:58:40 | GameSpyGamestatsServer] Now listening for connections on 0.0.0.0:29920...
[2021-10-06 10:58:40 | RegisterPage] Now listening for connections on port 9998...
[2021-10-06 10:58:40 | AdminPage] Now listening for connections on port 9009...
[2021-10-06 10:58:40 | GameStatsServerHttp] Now listening for connections on 127.0.0.1:9002...
[2021-10-06 10:58:40 | StorageServer] Checking for and creating database tables...
[2021-10-06 10:58:40 | Dls1Server] Now listening for connections on 127.0.0.1:9003...
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\User1\Desktop\MHTri Private Server\dwc_network_server_emulator-master\nas_server.py", line 269, in start
    httpd = NasHTTPServer(address, NasHTTPServerHandler)
  File "C:\Python27\lib\SocketServer.py", line 420, in __init__
    self.server_bind()
  File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "C:\Python27\lib\SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

[2021-10-06 10:58:40 | GameSpyNatNegServer] Server is now listening on 0.0.0.0:27901...
[2021-10-06 10:58:40 | GameSpyQRServer] Server is now listening on 0.0.0.0:27900...
[2021-10-06 10:58:40 | GameSpyServerBrowserServer] Now listening for connections on 0.0.0.0:28910...
[2021-10-06 10:58:40 | StorageServer] Now listening for connections on 127.0.0.1:8000...

Hope this helps and someone has a solution
Cheers!

**Comment by sepalani** [comment]
You probably have a service already running on port 80. You'll need to find it and disable it or change its port, if possible. You can use `netstat` to locate the service, (ex: `netstat -anop TCP | findstr ":80"`).
